---
title: "Using Grapho"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{using_grapho}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Using Grapho

Grapho will start recording a session once loaded using either

``` r
require(grapho)
```

or

``` r
library(grapho)
```

which will display a message welcoming you to the Grapho package. Grapho
will now record your console commands, plots you create, errors and
warnings.

You can view the files created by the grapho package by going to your
Grapho folder location as shown in the introductory messages. Another
way to get the location of the grapho folder is by running the below.

``` r
Sys.getenv('GRAPHO_FOLDER')
```

You can view a summary of the files contents of your grapho archive by
running.

``` r
parse_grapho_archive()
```

You can stop and start grapho collecting data by running the command

``` r
toggle_grapho()
```

## Data submission

Part of the WAYS research project is to examine your workflow. Part of
that is to collect anonymous data about your R session. If you wish to
send us your data then please run the R command

``` r
prepare_archive()
```

which will zip up the files in your grapho archive, tell you the
location of the zip file and the location of the form for you to submit
the zip files to.

## Data

Your data is anonymous. Your files are identified with a session and
user ID. Both the session and user ID are shown when you load in grapho.
You can also view the current user ID by running

``` r
Sys.getenv('GRAPHO_USER_ID')
```

and get your current session ID by running the below.

``` r
Sys.getenv('GRAPHO_SESSION_ID')
```

The user ID is generated by running

``` r
user_hash <- digest::digest(
  c(Sys.getenv('HOME'),
    Sys.getenv('LANG'),
    Sys.getenv('R_PLATFORM')),
  algo = 'sha512'
)

Sys.setenv(
  GRAPHO_USER_ID = substr(user_hash, 1, 40)
    )
```

where a sha512 hash is generated from a combination of your home
directory location, system language and the version of R you are using.
Your user ID is the first 40 characters of the hash.

Your session ID is generated by running

``` r
session_hash <- digest::digest(
  date(), algo = 'sha512'
)

Sys.setenv(
  GRAPHO_SESSION_ID = substr(session_hash, 1, 40)
)
```

which takes the first 40 characters of an SHA512 has of the current
date.
